import type { ChangeEvent } from 'react'
import { exampleRecipes } from '../data/exampleRecipes'

interface EmptyRecipeProps {
  onFile: (event: ChangeEvent<HTMLInputElement>) => void
  onExample: (path: string) => void
  error: string
}

export function EmptyRecipe({ onFile, onExample, error }: EmptyRecipeProps) {
  return (
    <section className="empty-panel">
      <div className="empty-recipes-panel">
        <div className="section-kicker">Bundled recipes</div>
        <h2>Choose a recipe</h2>
        <p>Start with one of the included examples.</p>
        <div className="example-list">
          {exampleRecipes.map(({ path, recipe }) => (
            <button type="button" className="example-list-item" onClick={() => onExample(path)} key={path}>
              <span>{recipe.title}</span>
              <b>↗</b>
            </button>
          ))}
        </div>
      </div>
      <div className="upload-target">
        <div className="target-mark" aria-hidden="true"><span /></div>
        <div className="section-kicker">Recipe card renderer</div>
        <h2>Upload a recipe JSON</h2>
        <p>Choose a structured recipe artifact generated by <code>recipe-card-structurer</code> to render its process matrix.</p>
        <label className="target-picker">
          <input type="file" accept="application/json,.json" onChange={onFile} />
          <span>Choose JSON file</span>
        </label>
        {error && <div className="import-error" role="alert">{error}</div>}
      </div>
    </section>
  )
}
